export const CATEGORY_OPTIONS = [
  "uncategorized",
  "income",
  "services",
  "food",
  "transport",
  "transfers",
  "social-security",
  "taxes",
  "financial",
  "shopping",
  "health",
  "education",
  "housing",
  "entertainment",
  "subscriptions",
  "personal-care",
  "cash",
  "other",
];

export const CATEGORY_RULES = [
  {
    category: "services",
    keywords: [
      "CENTRALES ELECTRICAS",
      "CENS",
      "AGUA",
      "ACUEDUCTO",
      "ALCANTARILLADO",
      "ASEO",
      "GAS",
      "VANTI",
      "GASES DEL ORIENTE",
      "INTERNET",
      "CLARO",
      "MOVISTAR",
      "TIGO",
      "WOM",
      "DIRECTV",
      "NETFLIX SERVICIO",
    ],
  },
  {
    category: "social-security",
    keywords: [
      "APORTES EN LINEA",
      "PILA",
      "PLANILLA INTEGRADA",
      "MIPLANILLA",
      "MI PLANILLA",
      "PAGO PLANILLA",
      "SOI",
      "ARUS",
      "ASOPAGOS",
      "SEGURIDAD SOCIAL",
      "SALUD PENSION",
      "SALUD Y PENSION",
      "PENSION OBLIGATORIA",
      "FONDO DE PENSIONES",
      "ARL",
      "CAJA DE COMPENSACION",
    ],
  },
  {
    category: "taxes",
    keywords: [
      "DIAN",
      "IMPUESTO",
      "RETENCION",
    ],
  },
  {
    category: "food",
    keywords: [
      "COMIDAS RAPIDAS",
      "NAN KING",
      "RESTAURANTE",
      "RESTAURANT",
      "COMIDA",
      "BURGER",
      "PIZZA",
      "CAFE",
      "CAFETERIA",
      "PANADERIA",
      "PASTELERIA",
      "ASADERO",
      "PARRILLA",
      "POLLO",
      "DOMICILIO",
      "RAPPI",
      "IFOOD",
      "MCDONALD",
      "KFC",
      "SUBWAY",
      "FRISBY",
      "CREPES",
      "JUAN VALDEZ",
      "TOSTAO",
    ],
  },
  {
    category: "transport",
    keywords: [
      "UBER",
      "DIDI",
      "CABIFY",
      "INDRIVE",
      "TAXI",
      "TRANSPORTE",
      "BUS",
      "TERMINAL",
      "PEAJE",
      "PARQUEADERO",
      "PARKING",
      "GASOLINA",
      "COMBUSTIBLE",
      "TERPEL",
      "TEXACO",
      "PRIMAX",
      "EDS",
    ],
  },
  {
    category: "financial",
    keywords: [
      "BANCOLOMBIA",
      "UPHOLD",
      "PEXTO",
      "DAVIVIENDA",
      "NEQUI",
      "DAVIPLATA",
      "BBVA",
      "SCOTIABANK",
      "COLPATRIA",
      "NU",
      "INTERES",
      "COMISION",
      "CUOTA DE MANEJO",
      "GMF",
      "RETEFUENTE",
      "COSTO TRANSACCION",
      "COBRO",
    ],
  },
  {
    category: "transfers",
    keywords: [
      "TRANSFERENCIA",
      "ENVIASTE A",
      "RECIBISTE DE",
      "LINA BACCA",
      "ANDRES ROJAS",
      "VALENTINA VACCA",
      "YADIR BITAR",
      "SANDRA PATRICIA",
      "DUVAN ALEJANDRO",
      "MIGUEL OSWALDO",
      "JAVIER FERNANDO",
      "GERMAN JAIMES",
      "JORGE ALBERTO",
      "VALERY MELIZA",
      "MAGALI CARDENAS",
      "MERCEDES PATRICIA",
      "PEDRO MANUEL",
      "KRISTIAN FELIPE",
      "LINDA LIZETH",
      "LINDA LIZETH CARDENAS",
      "LINDA LIZETH CARDENAS DAVID",
    ],
  },
  {
    category: "health",
    keywords: [
      "FARMACIA",
      "DROGUERIA",
      "CRUZ VERDE",
      "AUDIFARMA",
      "MEDICAMENTO",
      "CLINICA",
      "HOSPITAL",
      "EPS",
      "ODONTOLOGIA",
      "OPTICA",
      "SALUD",
    ],
  },
  {
    category: "education",
    keywords: [
      "UNIVERSIDAD",
      "COLEGIO",
      "MATRICULA",
      "EDUCACION",
      "CURSO",
      "DIPLOMADO",
      "LIBRERIA",
      "PAPELERIA",
      "UDEMY",
      "COURSERA",
      "PLATZI",
    ],
  },
  {
    category: "housing",
    keywords: [
      "ARRIENDO",
      "ADMINISTRACION",
      "CONJUNTO",
      "EDIFICIO",
      "INMOBILIARIA",
      "FERRETERIA",
      "HOGAR",
      "MUEBLES",
      "ELECTRODOMESTICOS",
    ],
  },
  {
    category: "entertainment",
    keywords: [
      "CINE",
      "CINEMA",
      "ROYAL FILMS",
      "CINE COLOMBIA",
      "TEATRO",
      "BAR",
      "DISCOTECA",
      "EVENTO",
      "JUEGOS",
      "STEAM",
      "PLAYSTATION",
      "XBOX",
    ],
  },
  {
    category: "subscriptions",
    keywords: [
      "NETFLIX",
      "SPOTIFY",
      "DISNEY",
      "HBO",
      "MAX",
      "AMAZON PRIME",
      "PRIME VIDEO",
      "YOUTUBE",
      "GOOGLE",
      "APPLE",
      "ICLOUD",
      "MICROSOFT",
      "OPENAI",
      "CHATGPT",
      "GITHUB",
      "FIGMA",
      "CANVA",
    ],
  },
  {
    category: "personal-care",
    keywords: [
      "PELUQUERIA",
      "BARBERIA",
      "SPA",
      "COSMETICO",
      "PERFUMERIA",
      "BELLEZA",
      "MAQUILLAJE",
      "GIMNASIO",
      "GYM",
    ],
  },
  {
    category: "cash",
    keywords: [
      "RETIRO",
      "CAJERO",
      "ATM",
      "EFECTIVO",
    ],
  },
  {
    category: "shopping",
    keywords: [
      "SUPERMERCADO",
      "EXITO",
      "CARULLA",
      "D1",
      "ARA",
      "JUMBO",
      "OLIMPICA",
      "MERCADO",
      "TIENDA",
      "AMAZON",
      "MERCADO LIBRE",
      "FALABELLA",
      "ALKOSTO",
      "KTRONIX",
      "PANAMERICANA",
      "COMPRA EN",
    ],
  },
];